### ISSUE TITLE
black box around cursor

### ISSUE THREAD

**Issue by coolemza** [FreeRDP/Remmina#1098]
There is black box around cursor. It apears on any cursor i can chose inside rdp session. 

* Client (OS name and version): Ubuntu 16.10
* Remmina version (remmina --version): 1.2.0-rcgit-17
* Desktop environment (GNOME, Unity, KDE, ..): Unity
* Connecting to (OS and version): Xubuntu 16.10
* Connecting via (RDP, VNC, ...): rdp
* RDP issues only, freerdp version (xfreerdp --version): dont know how to get it

 version 1.1.2 in ubuntu 16.10 repository does not have this issue

**Comment by dankasak** [comment]
I'm seeing this issue too. I'm using freerdp-2.0.0_pre20161219 and remmina-1.2.0_rc18. These were the default versions chosen by Gentoo. I've just moved from Sabayon, which included version 1.1.2, and also didn't have this issue before.

**Comment by giox069** [comment]
1. Does this happens with VNC plugin also? Can anyone test VNC?
2. Which video card and driver are you using? Please post the output of `lspci -nnk | grep -i vga -A3`
3. If possible, attach a screenshot or a photo (or part of it) of the cursor with the black box around.

Thank you.

**Comment by dankasak** [comment]
Hi giox069. Thanks for your time.

1) I just tested with VNC, and this bug does _**not**_ appear to affect the VNC plugin

2) 00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 520 [8086:1916] (rev 07)
        Subsystem: Dell HD Graphics 520 [1028:06db]
        Kernel driver in use: i915
        Kernel modules: i915

3) 
![remmina_cursor](https://cloud.githubusercontent.com/assets/7410307/23634718/e7a29e62-031f-11e7-98d1-a4dbd7daf7ce.png)

I'm using the exact same kernel version ( 4.9.9-rt6 ), intel drivers ( git ), and *almost* the same mesa build ( git ) that I was using under Sabayon ( where the cursor was working fine ). I've also tested under Gnome 3 ( latest version ), and Enlightenment ( latest version ) using both GL compositing and software compositing. All combinations show this cursor corruption - which at least appears to rule out mesa.

Interestingly, when I used various apps to generate screenshots, the cursor didn't appear at all - until I tried The Gimp, and then *only* when I said to do a full-screen screenshot *and* include the cursor. I had assumed the cursor in a remmina session was separate from the system cursor, and implemented in software, but this implies that the cursor in remmina *is* the X cursor. If there is a software fallback available, that might fix things?

**Comment by giox069** [comment]
As you noticed, the cursor in remmina is the X (GTK+) cursor. There is no software fallback code.
I'm trying to find a machine where I can reproduce the problem. I have many Dell machines at work, which one is the affected one?

**Comment by dankasak** [comment]
My particular Dell is a Latitude E7270, but I would expect if it was related to graphics drivers, then anything with an Intel GPU would be affected.

**Comment by antenore** [comment]
Can you please test with xfreerdp?

**Comment by giox069** [comment]
I can see that both @coolemza and @dankasak are connecting to a linux RDP server. Which RDP server are you using? If possible, please test also with xfreerdp commandline tool, as suggested by @antenore.
I did some tests in a couple of old machines with i915 driver... but I can't still reproduce the problem.

**Comment by dankasak** [comment]
xfreerdp is also affected.

I'm using xrdp as the RDP server. Other RDP clients are still ok with it - eg Window's native RDP client, and 'mobaXterm'. Older versions of clients xfreerdp and remmina are also still ok.

**Comment by dankasak** [comment]
I've just tested with the modesetting driver instead of the intel one, and this combo is also affected.

**Comment by coolemza** [comment]
im using latest xrdp

00:02.0 VGA compatible controller [0300]: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller [8086:0126] (rev 09) 
        Subsystem: Lenovo 2nd Generation Core Processor Family Integrated Graphics Controller [17aa:21da]                                            
        Kernel driver in use: i915                                                                                                                   
        Kernel modules: i915

**Comment by giox069** [comment]
I have been able to reproduce the problem connetting from Ubuntu 16.04 (nvidia driver) to Xubuntu 17.04 xrdp. And I have the same problem with xfreerdp. The problem seems to be in libfreerdp: I will open an issue to the FreeRDP team as soon as possible.

**Comment by giox069** [comment]
Issue opened here: https://github.com/FreeRDP/FreeRDP/issues/3863

**Comment by dankasak** [comment]
thanks :)

**Comment by giox069** [comment]
libfreerdp has been fixed [today](https://github.com/FreeRDP/FreeRDP/pull/3870) for this issue, thank you @akallabeth.
We need also to update freerdp packages on  remmina-next-ppa, but we have not yet scheduled this update (Cc: @nastasi)

**Comment by giox069** [comment]
FreeRDP packages on remmina-next PPA are updated now.
You can test it.

**Comment by ic3d** [comment]
Hi @dankasak we are reviewing old open issues, can you confirm this one is now fixed? Thanks!

**Comment by inkarkat** [comment]
I still have the issue using Remmina 1.2.0-rcgit-24 installed via snap (via _edge_ channel) on Ubuntu 16.04 LTS. 

Also, the upstream issue FreeRDP/FreeRDP#3863 is still open. Are you sure it's been fixed there?

**Comment by ic3d** [comment]
This issue should be fixed, as upstream one FreeRDP/FreeRDP#3863 is now closed. Can @inkarkat confirm? Thanks!

**Comment by inkarkat** [comment]
Unfortunately, I still have the same problem with the latest snap from edge, Remmina 1.2.30 (git c58143f):

    $ snap list
    Name     Version    Rev   Tracking  Developer  Notes
    core     16-2.32.8  4650  stable    canonical  core
    remmina  1.2.30     1425  edge      remmina    -

**Comment by antenore** [comment]
@inkarkat do you have wayland or xorg?

**Comment by inkarkat** [comment]
@antenore I'm still on Ubuntu 16.04, so that's xorg 1:7.7+13ubuntu3. I've never tried wayland so far.

BTW, the "black box" for me is more like garbled previous desktop contents; mostly it's the mouse pointer painted several times, and existing window contents with an offset of some pixels.

**Comment by antenore** [comment]
WARNING:
The Remmina project is moving to gitlab.com, in order to keep receiving notification about this issue,
you should have a gitlab account and link it to github.
The migration will happen in the next days.
Thanks for your support and understanding.

cc @antenore @coolemza @dankasak @giox069 @ic3d @inkarkat
