### ISSUE TITLE
Remmina always remember password

### ISSUE THREAD

**Issue by Inglebard** [FreeRDP/Remmina#1224]
Hi,

Just a minor issue.

On Archlinux (Gnome) with remmina version 1.2.0-rcgit-19 (git rcgit-19), it seems when I connect to an host with SSH, it remember password even if I don't check the checkbox to remember password.

**Comment by antenore** [comment]
Can you please test the rcgit-20?

**Comment by Inglebard** [comment]
Hi, 
I just compile and check, the issue is still present. (1.2.0-rcgit-20 (git rcgit-20))

**Comment by antenore** [comment]
Sorry...

I think that this is fixed by #1250 that I've forgotten to merge in the next branch (so it's not included in rcgit-20).

May I ask you, when you have time and the wish to do it, to test that PR? 
You should also remove the password from the keychain or in the .remmina file. If you need assistance on this let me know.

**Comment by giox069** [comment]
PR #1250 is merged into "next" now. Having 5 confirmation button is a bit confusing? Maybe not when we have the most used/wanted selected by default.  What do you think?

**Comment by Inglebard** [comment]
Hi,
I just test the latest version (e6c7efea7ca8d847f7171b2af57b8a50992177b4).
The issue still remain.
When you connect to a server without password, it prompt a password input. Check the checkbox or not will always save password.

**Comment by antenore** [comment]
OK, I'll try to reproduce and fix this in the next days

**Comment by giox069** [comment]
I have just pushed a [fix](https://github.com/FreeRDP/Remmina/commit/bcdfa2ddf4c241cede66ead961d367e6964ff3fa) on the "next" branch. Please check it, if you can, thank you.

**Comment by Inglebard** [comment]
Hi,
I just test and it works as expected.
Thanks.
