### ISSUE TITLE
RDP session anytime crash

### ISSUE THREAD

**Issue by SergeyDjam** [FreeRDP/Remmina#1280]
Client - ROSA Linux Fresh 8.1/9
Remmina version - Remmina - Version 1.2.0-rcgit-20 (git rcgit-20)
Desktop environment - KDE
Connecting to Windows 2003 server
Connecting via RDP (RDP/TLS)
RDP issues only, freerdp version (xfreerdp --version): FreeRDP version 2.0.0-dev (git n/a)

Anytime RDP session crash

**Comment by giox069** [comment]
This seems to be a duplicate of issue #1270, which is in turn a FreeRDP problem. We will update libfreerdp on the PPA as soon as we release Remmina 1.2.0-rcgit-21.

**Comment by giox069** [comment]
@SergeyDjam is this issue fixed with remmina 1.2.0-rcgit-21 ?

**Comment by SergeyDjam** [comment]
I need still time for testing and check

**Comment by SergeyDjam** [comment]
Testing of operation for more than 10 PCs showed that the problem is not solved. It became more rare to be shown, but it is not solved

**Comment by giox069** [comment]
Remmina closes completely (program crash), or only the single connection is closed and the remmina main window remain active?

**Comment by SergeyDjam** [comment]
Only the window with the session of RDP is closed

**Comment by giox069** [comment]
Try to launch remmina from a terminal. Look at the text output when remmina disconnects.
If you find errors like **ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED** [**0x2000C**], then the problem is in libfreerdp. It's already reported at their sites with FreeRDP issues [2190](https://github.com/FreeRDP/FreeRDP/issues/2190) and [3528](https://github.com/FreeRDP/FreeRDP/issues/3528).
And we can't do almost anything here in remmina. We can help the FreeRDP team, for example, by finding a reproducible way to make the problem happens.

**Comment by SergeyDjam** [comment]
In 1.2.0-rcgit-26 works rather stablly

**Comment by antenore** [comment]
WARNING:
The Remmina project is moving to gitlab.com, in order to keep receiving notification about this issue,
you should have a gitlab account and link it to github.
The migration will happen in the next days.
Thanks for your support and understanding.

cc @giox069 @SergeyDjam
