### ISSUE TITLE
vertical text issue with excel

### ISSUE THREAD

**Issue by tomarch** [FreeRDP/Remmina#345]
I use the lastest gtk3 branch, compil with AUR on archlinux X86_64
The guest is an windows 7 32 bits with office excel 2010

When the text in a cell is set verticaly, only the first letter appear.

This issue doesn't appear with xfreerdp command line.

**Comment by tomarch** [comment]
I have build remmina and freerdp todat, and this problem is solved.
Thx

**Comment by giox069** [comment]
I'm still having the problem, both with newest xfreerdp `/gdi:sw` and remmina. So I will leave the freerdp issue open.

**Comment by giox069** [comment]
I have just submitted a pull request for freerdp
https://github.com/FreeRDP/FreeRDP/pull/2734
