### ISSUE TITLE
Remmina not showing entire desktop, Windows Remote Desktop Connection does.

### ISSUE THREAD

**Issue by penalvch** [FreeRDP/Remmina#534]
What is expected to happen with Remmina in Vivid, is RDP to a Vivid server with xrdp, x11vnc, and using gnome-flashback (Metacity) is it shows the entire desktop successfully.

What happens instead is it is missing the lower ~5% on the right hand side (truncating part of the gnome-panel icons) and the bottom (where the windows are) as per the attached screenshot. This does not happen with Windows 8.1 RDC so this is a Remmina issue. Tried toggling Scaled Mode, no change.

Remmina Desktop Preference > Basic tab > Resolution Use client resolution > Color depth High color (16 bpp), High color (15 bpp), and 256 colors (8 bpp) > Advanced tab > Quality Best (slowest), Sound Off > Security Negotiate > all other configurations unchecked.

Vivid setup:
sudo apt-get -y install xrdp gnome-session-flashback gnome-flashback x11vnc && sudo apt-get -y remove vnc4server && sudo nano /etc/xrdp/xrdp.ini

Change the top part to the following:
#START
[globals]
bitmap_cache=yes
bitmap_compression=yes
port=3389
crypt_level=high
channel_code=1
max_bpp=24
#black=000000
#grey=d6d3ce
#dark_grey=808080
#blue=08246b
#dark_blue=08246b
#white=ffffff
#red=ff0000
#green=00ff00
#background=626c72

[xrdp1]
name=sesman-X11vnc
lib=libvnc.so
username=ask
password=ask
ip=127.0.0.1
port=5900
#END

sudo nano /etc/systemd/system/x11vnc.service
#START
After=multi-user.target

[Service]
Type=simple
ExecStart=/usr/bin/x11vnc -loop -auth guess -rfbauth /home/USERNAME/.vnc/passwd -rfbport 5900 -forever -nevershared -repeat

[Install]
WantedBy=multi-user.target
#END

sudo chmod u+x /etc/systemd/system/x11vnc.service
sudo systemctl daemon-reload
sudo systemctl enable x11vnc.service
sudo reboot now

ProblemType: Bug
DistroRelease: Ubuntu 15.04
Package: remmina 1.1.1-1ubuntu1
ProcVersionSignature: Ubuntu 3.19.0-11.11-generic 3.19.3
Uname: Linux 3.19.0-11-generic x86_64
NonfreeKernelModules: wl
ApportVersion: 2.17-0ubuntu1
Architecture: amd64
Date: Fri Apr  3 17:06:25 2015
InstallationDate: Installed on 2015-04-02 (1 days ago)
InstallationMedia: Ubuntu 15.04 "Vivid Vervet" - Beta amd64 (20150326)
ProcEnviron:
 TERM=xterm
 PATH=(custom, no user)
 XDG_RUNTIME_DIR=<set>
 LANG=en_US.UTF-8
 SHELL=/bin/bash
SourcePackage: remmina
UpgradeStatus: No upgrade log present (probably fresh install)
![screenshot](https://cloud.githubusercontent.com/assets/8216601/6990233/9e486e12-da2d-11e4-8661-b8391bc5085e.png)

**Comment by giox069** [comment]
Please try the current version of remmina (1.2). See the [Remmina Wiki](https://github.com/FreeRDP/Remmina/wiki) which explains how to install the remmina-next PPA, available also for vivid.
If the problem persists after upgrading remmina to 1.2, can you provide some instruction on how to setup a xrdp server on vivid ?

**Comment by penalvch** [comment]
glox069, thanks for the fast response.
>"Please try the current version of remmina (1.2). See the Remmina Wiki which explains how to install the remmina-next PPA, available also for vivid."

Setting up the Remmina PPA is going to be a while as I need to stand up a virtual environment for that. However, I did provide keyboard click-for-click instructions on how to set up an xrdp server in Ubuntu Vivid. Were they not clear enough to follow verbatim?

**Comment by giox069** [comment]
Ok, thank you. Now I understand what the line "vivid setup" means :)

**Comment by giox069** [comment]
I hate when github automatically closes an issue after a code merge, I'm sorry for that, and I'm reopening it.
I have just committed a big patch to remmina "next" branch (1.2.X). But you shoud use the PPA (ater it will update). I don't think this patch will be on vivid remmina 1.1, because:
1. It's a new feature. RDP desktop resizing was never supported by Remmina 1.1 before today. Distro maintainers won't accept a new feature to an existing package. Only bug/security fixes.
2. It will take a certain amount of coding time to backport to 1.1, and currently I wonder if it's worth it: fixing and updating Remmina 1.2 is taking all our limited development time.

Le us know if it's fixed.

**Comment by penalvch** [comment]
giox069:

>"I hate when github automatically closes an issue after a code merge, I'm sorry for that, and I'm reopening it."

No worries on my end. It's a github'ism. :D

>"I have just committed a big patch to remmina "next" branch (1.2.X). But you shoud use the PPA (after it will update)."

Thanks for the fast code patch. When the PPA is updated, I'll test it out via VM and advise back on this.

>"I don't think this patch will be on vivid remmina 1.1, because: 1. It's a new feature. RDP desktop resizing was never supported by Remmina 1.1 before today."

I wouldn't classify the patch as introducing a new feature, but a bug fix to an outstanding one.

>"Distro maintainers won't accept a new feature to an existing package. Only bug/security fixes."

Ubuntu has a mechanism for backporting both security and features via the SRU process https://wiki.ubuntu.com/StableReleaseUpdates . It says one thing, but the Ubuntu folks typically request it goes through SRU either way for an up/down vote first, then go through backport if declined for an SRU.

>" 2. It will take a certain amount of coding time to backport to 1.1, and currently I wonder if it's worth it: fixing and updating Remmina 1.2 is taking all our limited development time."

Well, if 1.2 doesn't suffer from any regressions from 1.1 (e.g. it has documented functionality unit tests) why not just request 1.2 be loaded into Vivid?

**Comment by penalvch** [comment]
giox069, just to advise, I updated to Wily and the issue persists.

Despite this, given Wily is the latest version of Ubuntu and still in development, could the stable 1.2 branch fixes be backported to Wily's 1.1.2? Or, if this is too much effort, would 1.2 be backported in whole to Wily?

apt-cache policy remmina
remmina:
  Installed: 1.1.2-2ubuntu2
  Candidate: 1.1.2-2ubuntu2
  Version table:
 *** 1.1.2-2ubuntu2 0
        500 http://us.archive.ubuntu.com/ubuntu/ wily/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by giox069** [comment]
The remmina-next PPA is currently not available for wily.
@dktrkranz is it possible to update it ? Also @dktrkranz please note: we have a branch of remmina  which does not depends on freerdp, but it brings its own copy of freerdp inside. It will be merged in the "next" branch in 4-5 days. Could it be used into the remmina-next PPA ?

**Comment by penalvch** [comment]
glox069, problem confirmed resolved via https://launchpad.net/~remmina-ppa-team/+archive/ubuntu/remmina-next :
remmina 1.1.1-1+761+next+201506260301~ubuntu15.04.1

**Comment by dktrkranz** [comment]
Sure @giox069, I just scheduled the builds.

For the embedded freerdp, are you going to release a 1.2 version with it? Normally this is discouraged for security and maintenance implications. Are there specific reasons to do so (e.g. too frequent ABI breakages) ?

**Comment by giox069** [comment]
@dktrkranz thank you for scheduling the wily build on the remmina-next PPA.
About embedded FreeRDP: I'm opening a new issue now explaining all the things we did and we would like to do. You will receive a new notification later.
