### ISSUE TITLE
Clipboard + Windows 2008 Server R2 SP1 + Google Chrome

### ISSUE THREAD

**Issue by lestevam** [FreeRDP/Remmina#583]
HOST: Elementary OS Freya
RDP: Windows Server 2008 R2 SP1
Last compilation: 06/09/2015

If I try to copy any text of the google Chrome's address bar the Remmina clears the clipboard, enabling the debug window appeared the following messages:

[RDP] Cannot paste now, I'm transferring clipboard data from server. Try again later

The text to be copied is a URL and not think it's big enough to deliver this message.

I performed a test connectando directly by xfreerdp and the error does not happen.

The button to disable synchronization of the desktop is not working, but realized the modification directly in the configuration file, but even disabling and enabling again did not correct the problem.

**Comment by giox069** [comment]
Thank you for reporting. I have been able to reproduce the bug. The clipboard support has currently some problems and needs to be fixed. See also issue #556.
I'm marking this issue as a bug and I hope I will be able to fix in the next weeks.

**Comment by codeocelot** [comment]
I can confirm the bug is happening to me on my ubuntu 15.04 host w/ Win Server 2012 R2 Datacenter (Azure VM).  Toggling 'Disable sync' under 'Advanced Settings'  didn't help. 

I don't recall this always being an issue.  I'll keep an eye out for what variable might be causing this.

**Comment by dove-young** [comment]
The clipboard issue is happening in my environment.  Here is the environment info

* remmina.x86_64 1.2.0-0.5.git.b3237e8.fc22
* Fedora 22 KDE , 4.0.6-300.fc22.x86_64
* Windows 2008 R2

**Comment by giox069** [comment]
I just pushed a small fix. Ubuntu's PPA will update in one day.

**Comment by blakev** [comment]
This is still an issue for me.

Host: xubuntu 15.10 x64
VM: Windows Server 2003/2008/2012

**Comment by giox069** [comment]
@blakedev: are you still having the copy&paste from chrome address bar with the latest version of remmina from the PPA ? Can I close this issue ?

**Comment by blakev** [comment]
@giox069 The problem is mitigated when running remmina as sudo, so things have been going smoothly (for the most part) for the last month.

Thanks for your work!
