### ISSUE TITLE
Initial screen wonky opening VNC client

### ISSUE THREAD

**Issue by vab3** [FreeRDP/Remmina#69]
My screen always comes up like this: 

http://vab3.smugmug.com/photos/i-KtVgsK9/0/L/i-KtVgsK9-L.png

If I resize the screen or click the "resize" button, then things work properly.  Ubuntu 12.04. Remmina 0.9.99.1.  Tight VNC 2.5.1 for Windows.  Let me know if I can give you more information to help. Great software package.

**Comment by muflone** [comment]
Does this issue still exists? It should be fixed a lot of time ago.

If this issue persists please reopen. For the moment I'm closing it.

**Comment by willbprog127** [comment]
This issue still exists for me.

**Comment by muflone** [comment]
@willbprog127 what version of remmina do you use?

**Comment by giox069** [comment]
The issue reported on the 1st post screenshot should has been solved some month ago. All recent version of remmina (1.1.X and 1.2.X) should work. Please see the [Remmina Wiki](https://github.com/FreeRDP/Remmina/wiki) on how to upgrade.

**Comment by willbprog127** [comment]
This issue is still happening with the Ubuntu PPA, Remmina version 1.2.0-rcgit.2:
![remmina-problem-01](https://cloud.githubusercontent.com/assets/1296250/5599758/02c75de2-9282-11e4-9d1c-eb137734cc72.png)

**Comment by michaelblyons** [comment]
@giox069 Thanks for the tip. I'm on the PPA for 1.1.2, now and the bug is gone for me.

**Comment by muflone** [comment]
@willbprog127 exactly what defect do you see?
What should we observe from the screenshot?

**Comment by willbprog127** [comment]
@muflone The server image should be centered in the window, as it was in the past.  I'm just trying to help, but I really do not have any interest in Remmina anymore.  Thanks for your help.

**Comment by muflone** [comment]
@giox069 what do you think about this issue?
In the upper image the desktop is upper left cornered but this doesn't seem the previous wrong alignment issue.

**Comment by giox069** [comment]
1. This is not the same issue as the 1st screenshot post, it's different. I think this thread can be closed, and we should understand whether we need to reopen a different issue or no.
2. I cannot reprocude it, I'm sorry. I will try in the next days. Also please note: many GTK functions related to centering and scaling the winfo (GtkAlignment object) has been recently deprecated in GTK 3.14. So I'm trying to understand how to convert them to the newer gtk, working on remmina_connection_window.c
3. Another thing I cannot understand: remmina should make a black background around the windows image. Why is the extra background space gray in the screnshot ? I think this should be investigated AFTER the port to GTK3.14 of remmina_connection_window.c.
I'm for closing this issue now, due to: post#1 is fixed AND loss of interest by @willbprog127.
We will reopen, if needed, after the port of remmina_copnnection_window.c to GTK3.14.
Ok ?
