### ISSUE TITLE
GTK 3.20 VTE3 Remmina shows blank terminal

### ISSUE THREAD

**Issue by rlees85** [FreeRDP/Remmina#835]
It seems that the version of VTE3 that is required for Gnome Terminal (3.20) no longer works with Remmina. When making a SSH connection, Remmina asks for the password as normal but then the terminal window is just black with a white square cursor in the top left.

- Version of VTE3 that is known to not work with Remmina: 0.44 [libvte-2.91.so.0.4400.1]
- Version of VTE3 that does work with Remmina: 0.42 [libvte-2.91.so.0.4200.5]

**For further information please see:**
[https://bbs.archlinux.org/viewtopic.php?id=211403](https://bbs.archlinux.org/viewtopic.php?id=211403)
[https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=820303](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=820303)

Are there any plans to get Remmina to work with the latest VTE3? Miss being able to use Remmina, a lot!

**OS details:**
Arch Linux (all packages up to date as of 16/04/2016)
Also seems to affect Debian SID
Remmina - Version 1.2.0-rcgit.11 (git n/a)
Cinnamon 2.8.8 / GTK3.20
Using SSH connections, problem is broken terminal output/input

I have tried re-compiling the package locally using Arch Build System - doesn't help

Thanks!

**Comment by antenore** [comment]
Thanks for the report, we will take a look asap.

**Comment by thewarden** [comment]
I'm also experiencing the same issue when trying to use Remmina for SSH.

**OS details**

Arch Linux (all packages up to date as of 2016-04-18)
Remmina - Version 1.2.0-rcgit.11 (git n/a)
gnome 3.20.1-1 / gdm 3.20.0-1 / GTK 3.20.3-1 / vte3 0.44.1-1

**Comment by antenore** [comment]
I've replicated the issue as well, but I didn't identify the root cause yet.

I thought the cause was some deprecated symbols, but none of the ones **documented** is used by Remmina.

It could be some non documented deprecated symbols or a bug in vte.

In both cases it would be nice to test another non-GNOME vte based terminal, if you guys have time to test this it would be great.

In the next days I should have some time to investigate further this issue

**Comment by rlees85** [comment]
Pantheon-Terminal works - and that is VTE3 based. Will try some more... thanks for looking into it by the way. Shame it is something non-trivial - by the looks of it.

**Comment by antenore** [comment]
I'll test asap on arch this commit d1e914a, I'm also adding new features and color palettes (tango, gruvbox, linux, solarized and xterm).

If anybody else wants to try out... (compiling instructions in the wiki , just substitute "next" with "vte3")

**Comment by rlees85** [comment]
Unfortunately, it did not work for me...

Remmina in help > about is showing d1e914a as the version too, so I think I built it right

**Comment by antenore** [comment]
Yes, you're right, it doesn't work (yet), I'm diving into it right now.

**Comment by antenore** [comment]
I didn't give up yet, but I'm not far, because I'm quite lost.

I just opened a bug report to the VTE team in the hope they will help me.

https://bugzilla.gnome.org/show_bug.cgi?id=765382

I'll continue to investigate but it'll probably take some time.

**Comment by rlees85** [comment]
Again your help is appreciated :) I understand your doing this out of your spare time and I also understand that I use Archlinux at my own risk. If there is anything (basic - I am not great at coding, especially in c) I can do to help please let me know.

**Comment by antenore** [comment]
Solved!

At the moment it works inside the vte3 branch, as we are still fixing other issues related with GTK+-3.20, we won't commit this in the "next" branch for some more days.

A huge thanks to the VTE team.

**Comment by rlees85** [comment]
Confirmed :) compiled on the vte3 branch this morning and works perfectly. Thanks again !

**Comment by antenore** [comment]
Cool! Can you please update the Arch forum thread?

We will merge into the "next" branch asap

**Comment by max72bra** [comment]
hi antenore and thanks for all this.
my setup is virtually identical to rlees85 but +1 problem solved here

**Comment by rollopack** [comment]
Thanks, I can confirm the problem is related to VTE3 in Debian too.

Installing libvte-2.91 from stable (0.38.1-2) make remmina working again with ssh.
But the bug still persist with the new vte version 0.44.1-1 from unstable

**Comment by antenore** [comment]
@rollopack Did you try to compile yourself the vte3 Remmina branch? 

The fix is still under testing and we are also preparing other corrections before to merge in the remmina master (next)

**Comment by rollopack** [comment]
@antenore No, I haven't tried

**Comment by antenore** [comment]
We will release a new "next" version as soon as we will fix the command line parsing issues we have with gtk+-3.20 and it'll include the vte patch as well.

Stay tuned.

**Comment by rlees85** [comment]
Not sure if I should raise a new issue, but it seems after closing a SSH connection the CPU usage gets pegged to 100% on one core with the remmina process being the culprit. I will try and get more details and raise another issue, but just a early heads up

**Comment by antenore** [comment]
Yes, please, another issue is better,

**Comment by antenore** [comment]
As a side note for the bug report.

Reopening the SSH connection bring down again the CPU consumption
