### ISSUE TITLE
Toggle Fullscreen Multiple Monitors returns to Primary

### ISSUE THREAD

**Issue by imperimus** [FreeRDP/Remmina#864]
I primarily use RDP but have the same with SSH windows too. I use tabbed mode but normally move the window to my second monitor and toggle full screen. Up until about a month ago it use to work faultlessly but now this almost every time I press the toggle full screen or control_r+f this makes it full screen on the primary monitor. Very rarely it works as expected.

Kernel: 3.19.0-32-generic x86_64 (64 bit) 
Desktop: Cinnamon 2.8.8
Distro: Linux Mint 17.3 Rosa
remmina - Version 1.2.0-rcgit.11
This is FreeRDP version 2.0.0-dev

**Comment by fknipp** [comment]
I observe the same problem here:

Linux Mint 17.2 Rafaela
Kernel 3.16.0-38-generic #52~14.04.1-Ubuntu SMP x86_64
Remmina 1.2.0-rcgit.13
Cinnamon 2.6.13

I found the following workaround: After toggling to full screen, when the remote desktop is shown on the primary display, I can move the application to the other monitor using the Cinnamon task bar:

 1. Right click on the desktop name in the task bar. 
 2. **Move to other monitor** (or something similar, it's _Zu anderem Bildschirm verschieben_ in German)

**Comment by ic3d** [comment]
Hi @imperimus @fknipp this issue should now be fixed (see issue #124 ). Can you confirm? Thanks!

**Comment by ic3d** [comment]
I'm closing this issue because it probably afflicts an old version of Remmina. Feel free to open it again if needed.

**Comment by nkichukov** [comment]
This is still happening with remmina-1.2.0_rc29-r1 and xfce4. Please, reopen it.
