### ISSUE TITLE
Full screen switches to the monitor on the left (regression)

### ISSUE THREAD

**Issue by lnicola** [FreeRDP/Remmina#873]
This sounds similar to #241, but for me it regressed when upgrading from 1:1.2.0rcgit.11-2 to 1:1.2.0rcgit.12-1 and the session moves to the monitor on the left, regardless of which is the primary one.

Please give us some details about the systems you are using:
* Client (OS name and version): Arch Linux x64
* Remmina version (remmina --version): 1.2.0-rcgit.11 (git n/a)
* Desktop environment (GNOME, Unity, KDE, ..): GNOME
* Connecting to (OS and version): CentOS 7 Xrdp
* Connecting via (RDP, VNC, ...): RDP
* RDP issues only, freerdp version (xfreerdp --version): 2.0.0-dev (git c3ce0c3)

**Comment by lnicola** [comment]
Actually, it doesn't seem to matter which monitor is the primary one. It moves to the one on the left.

**Comment by Ronaldho80** [comment]
I have exactly the same issue. Remmina switches to the left monitor. Sometimes, it goes to the right one, but this seems randomly.

My system is:
 * Ubuntu 16.04
 * Remmina version 1.2.0-rcgit.12 (git n/a)
 * Desktop GNOME
 * Connecting via VNC and RDP to Windows and Linux clients.

**Comment by orngreen** [comment]
Same Issue - Jumps to the monitor CONFIGURED as being the left one. Moving them around in display settings, Remmina will follow... But now I need to drag mouse over the "wrong" edge to change screen.

Remmina: 1.2.0-rcgit.12 (git n/a)
System: Linux Mint 17.3 Cinnamon 64-bit (Cinnamon version: 2.8.8)
Kernel: 3.19.0-32-generic
Graphic: Broadwell-U Integrated

**Comment by aseques** [comment]
I'm on kde and this doens't seem to affect me (under 1.2.0-rcgit.13)

**Comment by antenore** [comment]
I've probably an idea on the reason why we have this issue, but I'm quite busy with my job and I wont be able to investigate it further till the next week.

Really sorry :-( 

It'd be cool if you take a look at the git history (CAUTION: sometime it's quite chaotic) and try to identify what could cause such behaviour, usually are properties set at a window level.

The file that you should investigate is the remmina_connection_window.c

This is the remmina core and it's the one file that needs more refactoring, so it's normal that the code is quite a mess... Just to warn you of course.

**Comment by lnicola** [comment]
@antenore If I didn't do anything wrong, this broke in b8dd3910083f944d1545d860e8387c968cb208da .

**Comment by antenore** [comment]
Thanks for the help :-) This is a great community :-)

I see and [this](https://github.com/FreeRDP/Remmina/commit/b8dd3910083f944d1545d860e8387c968cb208da#diff-747cb94de21a01ac3da89dd6b89443b2L2361) is exactly the line I should modify, but doing it, I risk to have a regression on #817 

Where @Vladimir-csp asks to don't force GTK in placing the remmina window, because it should be the job of the window manager, and he is absolutely right from my point of view as well.

I don't think there is an easy way to solve it. I'll investigate on it ASAP.

**Comment by lnicola** [comment]
I should have looked into it earlier, but I had never tried git-bisect until now. By the way, Remmina builds quickly and it only took a couple of minutes to find the problem.

I'm more of a Windows guy and I know nothing about X11, GTK+ or multi-mon, but I noticed that applications run from a terminal tend to show up on the same display. I'm using GNOME. Is there a way to set windows as related to their "parents" so that the effect can be achieved?

**Comment by antenore** [comment]
Yep. That's probably the best solution to make everybody happy.

I'm opening a PR, unlucky I don't have your setup, so I cannot test it.

**Comment by lnicola** [comment]
Oh, that seems easy, thanks. However, I'll only be able to test it on Tuesday.

**Comment by antenore** [comment]
No rush. I'll keep the PR till needed.

**Comment by lnicola** [comment]
Hmm.. Nope, I have the same issue on branch `issue873_fullscreen`.

**Comment by antenore** [comment]
This is bad... I'll investigate further.
I'll merge the PR because that setting is good anyway.

**Comment by antenore** [comment]
@lnicola Regarding #241 what happen if you disable the workspaces (if it is even possible)?

Can you please test in different desktop environment (xfce4, cinnamon, lxde, kde, etc) ?

**Comment by lnicola** [comment]
I don't know what disabling the workspaces would mean in GNOME. I tested with Cinnamon and it behaves in the same way.

**Comment by antenore** [comment]
I'm checking again that commit. It's frustrating the fact I don't have a Windows multi monitor setup I can test :-\

**Comment by lnicola** [comment]
Do you have a Linux one? :grin:

**Comment by lnicola** [comment]
Are you sure you're not missing a `gtk_window_set_transient_for()` call?

**Comment by antenore** [comment]
> Are you sure you're not missing a gtk_window_set_transient_for() call?

If you are referring to to the warning: 

> Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged. 
 
No, this is caused by the authentication dialog.

The remmina connection window is more like a main window, it doesn't really need a transient parent (or I didn't understand what is a transient parent :-P everything is possible ) 

> Do you have a Linux one? :grin: 

The old nerds like me uses [Twisted nematic field effect LCD](https://en.wikipedia.org/wiki/Twisted_nematic_field_effect) :neckbeard: 

In few minutes I'll push another fix, I cannot test a multi monitor setup yet, so I count on you ;-)

**Comment by antenore** [comment]
Done. I'm evaluating also if it's the case to use gdk_window_set_fullscreen_mode, with  GDK_FULLSCREEN_ON_ALL_MONITORS

**Comment by lnicola** [comment]
>> Are you sure you're not missing a gtk_window_set_transient_for() call?

> If you are referring to to the warning:

> >   Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

> No, this is caused by the authentication dialog.

> The remmina connection window is more like a main window, it doesn't really need a transient parent (or I didn't understand what is a transient parent :-P everything is possible ) 

No, I was referring to your usage of `GTK_WIN_POS_CENTER_ON_PARENT` in bdca639b33dea5db1b895fa6f757095366d9a360. According to the [documentation](https://developer.gnome.org/gtk3/stable/GtkWindow.html#GtkWindowPosition), it means

> Center the window on its transient parent

Now that I've read about them, transient windows seem to be the solution for this:

> Dialog windows should be set transient for the main application window they were spawned from. This allows window managers to e.g. keep the dialog on top of the main window, or center the dialog over the main window. gtk_dialog_new_with_buttons() and other convenience functions in GTK+ will sometimes call gtk_window_set_transient_for() on your behalf.

Note that transient windows don't have to be dialogs.

> In few minutes I'll push another fix, I cannot test a multi monitor setup yet, so I count on you ;-)

I'll try it a bit later, but I don't see how it could work.

>  I'm evaluating also if it's the case to use gdk_window_set_fullscreen_mode, with GDK_FULLSCREEN_ON_ALL_MONITORS

If that does what it sounds like, please don't :grin:.

**Comment by lnicola** [comment]
> I'll try it a bit later, but I don't see how it could work.

Sorry, my bad, I somehow misread that commit. It fixes this issue, of course, but presumably regresses #817.

I still think setting the connection window as transient should work. I'd try it myself, but I didn't see a way to get a handle to the main one. Actually, I don't even see how `remmina_connection_window_init()` gets called, since it's `static` and doesn't seem to be used. Might be a GTK thing.

**Comment by antenore** [comment]
@Vladimir-csp please I really need your feedback, see at the end of the psot.

Well, let me try to explain what I see myself

remmina main call remmina_connection_window_open_from_filename and than (just filtering per remmina_connection_window), the function flow is:

> 06/22/2016 09:50:46 AM Trace calls: remmina_connection_window_open_from_filename
> 06/22/2016 09:50:46 AM Trace calls: remmina_connection_window_open_from_file
> 06/22/2016 09:50:46 AM Trace calls: remmina_connection_window_open_from_file_full
> 06/22/2016 09:50:50 AM Trace calls: remmina_connection_window_find
> 06/22/2016 09:50:51 AM Trace calls: remmina_connection_window_new_from_holder
> 06/22/2016 09:50:51 AM Trace calls: remmina_connection_window_class_init
> 06/22/2016 09:50:51 AM Trace calls: remmina_connection_window_init
> 06/22/2016 09:50:51 AM Trace calls: remmina_connection_window_initialize_notebook
> 06/22/2016 09:50:51 AM Trace calls: remmina_connection_window_update_tag
> 06/22/2016 09:50:51 AM Trace calls: remmina_connection_window_state_event
> 06/22/2016 09:50:51 AM Trace calls: remmina_connection_window_on_configure
> 06/22/2016 09:50:51 AM Trace calls: remmina_connection_window_on_configure
> 06/22/2016 09:50:51 AM Trace calls: remmina_connection_window_on_configure
> 06/22/2016 09:50:51 AM Trace calls: remmina_connection_window_focus_in
> 06/22/2016 09:50:51 AM Trace calls: remmina_connection_window_on_configure
> 06/22/2016 09:50:54 AM Trace calls: remmina_connection_window_focus_out

Both functions known nothing about the transient parent, so it should be GTK that deal with it.
So, centring the window in relation to its parent (set by GTK) should work, but probably, forcing this behaviour, it's something that does not work well with some strict window manager like dwm.

But it could also be that I'm saying a tons of bull**** , the thing is that we should rewrite the remmina_connection_window and restructure the rest of the code, to:

1) Understand well how it works
2) Reduce the actual spaghetti code.

The thing that remmina_connection_window is actually the Remmina core, it doesn't make things easier as we do what we can in our free time (after job and family duties and personally I'm even not a developer ;-) ).

So... Back to work now and I'll try to find a solution, but if you have any ideas/advices I'll love hearing about it. 

At the moment I think we can accept a regression on #817 @Vladimir-csp can you confirm? Or even better, can you test #904 ?

**Comment by lnicola** [comment]
> Both functions known nothing about the transient parent, so it should be GTK that deal with it.
So, centring the window in relation to its parent (set by GTK) should work [...]

I don't think I understand what you meant (or how GTK could know about the relationship between the two windows). The fix I tried now is something like:

```
diff --git a/remmina/src/remmina_connection_window.c b/remmina/src/remmina_connection_window.c
index f91e23a..d56d5f7 100644
--- a/remmina/src/remmina_connection_window.c
+++ b/remmina/src/remmina_connection_window.c
@@ -42,6 +42,7 @@
 #include <gtk/gtk.h>
 #include <stdlib.h>
 
+#include "remmina_main.h"
 #include "remmina_connection_window.h"
 #include "remmina_file.h"
 #include "remmina_file_manager.h"
@@ -2342,7 +2343,8 @@ static void remmina_connection_window_init(RemminaConnectionWindow* cnnwin)
        priv->view_mode = AUTO_MODE;
        priv->floating_toolbar_opacity = 1.0;
 
-       gtk_window_set_position (GTK_WINDOW(cnnwin), GTK_WIN_POS_CENTER_ALWAYS);
+       gtk_window_set_transient_for(GTK_WINDOW(cnnwin), GTK_WINDOW(remmina_main_get_window()));
+       gtk_window_set_position (GTK_WINDOW(cnnwin), GTK_WIN_POS_CENTER_ON_PARENT);
        gtk_container_set_border_width(GTK_CONTAINER(cnnwin), 0);
 
        remmina_widget_pool_register(GTK_WIDGET(cnnwin));
```

And works as intended as far as I can see, but is kind of ugly. If you think it's worth it, I can submit a PR with this change for @Vladimir-csp to try.

**Comment by antenore** [comment]
Cool! We will have time and room for improvements in the future, as far as it fixes an issue it's never ugly IMHO.

Thanks! :-)

I'll close my PR, if you want update also the AUTHORS and remmina/ui/remmina_about.glade files with your details if you want, or I can do my self creating a new release (or nothing at all if you don't want)

**Comment by lnicola** [comment]
For the record, I also tried

```
    gtk_window_set_transient_for(GTK_WINDOW(cnnwin), GTK_WINDOW(remmina_main_get_window()));
    gtk_window_set_screen(GTK_WINDOW(cnnwin), gtk_window_get_screen(GTK_WINDOW(remmina_main_get_window())));
```

, but it had no effect.

**Comment by Vladimir-csp** [comment]
Logic tells me that main window (connection list) and connection window (actual remote session(s)) should be common independent windows without any special hints. Only smaller dialog windows like password prompts or connection editor should be children to those windows from where the action was called.

With fullscreen... I do not know. Both behavior can be valid - fullscreen on one monitor or on all monitors. Maybe this could be made into option.

**Comment by antenore** [comment]
Thanks for your (both) support.
I must definitively find some time to understand better the doc and to ask some questions to some GTK+ gurus.

**Comment by Vladimir-csp** [comment]
Unfortunately, I do not know first thing about developing GTK interfaces, but I can point to a reference: Pidgin, it's general window architecture seems right. It has tabbed conversation windows and buddy list, with various child dialogs. Conceptually this is exactly what Remmina needs. May be Pidgin developers could give some advice.

**Comment by lnicola** [comment]
Oh wait. My proposed fix doesn't seem to work anymore after a full rebuild and it didn't really make sense.

My idea was to keep the connection window on the same monitor when going full-screen, but I confused the main window with the non-fullscreen connection window, if that makes sense.

**Comment by lnicola** [comment]
Using `gtk_window_fullscreen_on_monitor` doesn't seem to have any effect, but setting the window as transient does, kind of.

It depends on the position of the main window on my main monitor: if it's around the left or right side, going full-screen uses the current monitor. If it's near the center, going full-screen makes it move to the other one.

This makes no sense.

**Comment by ReddingZH** [comment]
I'm experiencing the same bug. Mostly Fullscreen opens on the left display. Is there any workaround we can use to make sure it opens on the desired display?

Client (OS name and version): Linux Mint 18 x64
Remmina version (remmina --version): 1.2.0-rcgit.14 (git n/a)
Desktop environment (GNOME, Unity, KDE, ..): Cinnamon
Connecting to (OS and version): Windows Server 2012 R2
Connecting via (RDP, VNC, ...): RDP

**Comment by lnicola** [comment]
@ReddingZH Well, I tried a couple of things, but they either introduce a regression for tiling WM users or only work some of the time, depending on the window position when you click full-screen. I didn't try anything else since my last post on this thread.

**Comment by antenore** [comment]
Back to business.

This issue happens only on Gnome (or gnome based/forked, like cinnamon). 

I've tried XFCE, LXDE, KDE, some different tiling WM, Lumina and Unity.
To me this sounds more a Gnome issue, so I'm going to drop the PR.

Anybody is willing to open a Gnome bug? I'll give all the needed support.

Thanks!

**Comment by rbeldin** [comment]
This started happening on Ubuntu 16.04 with KDE Neon 5.9.

**Comment by rbeldin** [comment]
This started happening on ubuntu 16.04 with KDE Neon 5.9.   I have 3 monitors - the internal laptop and two hdmi monitors.   If I drag remmina to screen 3 (right most) and I go to full screen in remmina, the full screen appears on 2.   Sometimes it will go on 1 but does not reliably go on 3.

**Comment by antenore** [comment]
#1103 will add an option in the appearance tab to choose the old or the new fullscreen behaviour.

Please test and let me know

**Comment by lnicola** [comment]
With "Fullscreen in the same monitor of the connection window" enabled, the full-screen window seems to be displayed on the same monitor as the connection window (that is, it works as intended).

I can't, however, disable that setting. If I disable it, Remmina behaves in the same way as above and it's again enabled in the preferences window.

**Comment by antenore** [comment]
I'll take a look.

**Comment by bab5470** [comment]
I'm seeing this issue in Remmina 1.2.0-rcgit-22 (git rcgit-22) on Ubuntu 17.10 but it ONLY happens when I have rainlendar (http://www.rainlendar.net/cms/index.php) alerts on my display. 

Dismiss all the alerts and it maximizes to the correct monitor.

I do have "Fullscreen on the same monitor as the connection window" checked and my connection window is on my second monitor.

Its almost like Remmina is seeing the Rainlendar alert window as its own "connection window". I can even move the rainlendar alert to my second monitor and it will get maximized there. (That's semi annoying though because I don't want rainlendar alerts over top of my RDP window)

**Comment by ulcha** [comment]
Same problems with  1.2.0-rcgit-27-0~remmina201802142315.r566cdf6.dd516ac4~ubuntu17.10.1 
Ubuntu 17.10 x64, wayland desktop (default)

**Comment by lnicola** [comment]
For anyone encountering this in GNOME, you can go to overview and move the full-screen Remmina window to another monitor.

**Comment by bab5470** [comment]
@lnicola For me what I end up doing is dragging my rainlendar alerts to the monitor I want remmina full screen on, connecting in full screen, then dragging my alerts back to my primary display. It works but its an annoying pain in the *** to do **every** time I connect. 

I don't know if this is a bug in how rainlendar works or a bug in remmina or maybe its a gnome bug? Whatever the case its **super** annoying and I'd love to not have to constantly implement the above work around.

**Comment by ulcha** [comment]
Since Ubuntu 18.04 problem for me is fixed, because Ubuntu switched from Wayland back to Xorg. Seems that Remmina (and a lot of other programs) are not fully compatible with Wayland display manager. I can again move windows around in the way i like.

**Comment by bab5470** [comment]
I am running xorg (not wayland) and I am still experiencing this. As indicated above though I am running an application called rainlendar which seems to be "confusing" Remmina as to where to place its window.

**Comment by antenore** [comment]
WARNING:
The Remmina project is moving to gitlab.com, in order to keep receiving notification about this issue,
you should have a gitlab account and link it to github.
The migration will happen in the next days.
Thanks for your support and understanding.

cc @antenore @aseques @bab5470 @lnicola @orngreen @rbeldin @ReddingZH @Ronaldho80 @ulcha @Vladimir-csp
