### ISSUE TITLE
Tray icon does not have  funktion in Plasma (KDE) and has very poor quality

### ISSUE THREAD

**Issue by husisusi** [FreeRDP/Remmina#883]
- Client: Arch Linux (Up to date)
- Remmina version : 1.2 rcgit11
- Desktop environment: KDE 5.22.0

Tray icon does not have  funktion in Plasma (KDE) and very poor quality
![screenshot_20160530_222025](https://cloud.githubusercontent.com/assets/8606735/15657807/d6731060-26b4-11e6-8c1d-519f7e44193c.png)
##

**Comment by antenore** [comment]
@husisusi we are discussing this between us.

The tray icon needs a complete review but doing it the right way, respecting all the Desktop Environments guidelines out there it's a puzzle.

 IMHO we should even remove this icon (completely), obviously, if you want to participate in the discussion and/or you have ideas, you are more than welcome.

Thanks for the report.

**Comment by antenore** [comment]
https://github.com/FreeRDP/Remmina/wiki/Systray-menu as reference

**Comment by antenore** [comment]
Andreas just made a change (#894) that should fix this issue, but I'm not sure that you will see it till the next remmina release, except if you compile yourself.

**Comment by husisusi** [comment]
I just compiled it and did a test.Change 894 did not fix this issue.

**Comment by antenore** [comment]
OK, it's a pity. I think you should have a remmina icon in your theme. At least, it's how the patch is supposed to work. If you have a remmina icon in your theme it will use it, otherwise it'll fallback to the standard one that comes with remmina

@wa4557 do you agree about this?

If I'm right we cannot do that match.

**Comment by wa4557** [comment]
Yes exactly that's how it supposed to work. You need your icon theme to provide a panel icon named remmina-panel then it should change.

Thinking of it: what do you guys think about a different icon for the panel (I would argue that a monochrome icon would be best). I could give it a try if you wish

**Comment by antenore** [comment]
Yes, why not! Some time ago I asked to a professional designer some new icons, but the result wasn't impressive (  #608 )

@giox069 @larchunix @weberhofer what do you think?

**Comment by giox069** [comment]
Yes, @wa4557 a new monochrome icon to try for the system tray would be very appreciated, thank you.

**Comment by weberhofer** [comment]
A freshup would be good, so: yes.

**Comment by wa4557** [comment]
How about something like this, taken from your logo
![remmina-panel2](https://cloud.githubusercontent.com/assets/6475757/15984568/eae72160-2fd0-11e6-907d-36b201ef4db1.png)

**Comment by antenore** [comment]
Personally I love that logo, so for me it's a GO. Good idea :-)

Can we see it in the notification area ? 

The best is to create a new branch, so that we can build, tests and send some screenshoots.

If you need support let me know.

**Comment by wa4557** [comment]
Alright. I opened a new pull request :+1:

**Comment by antenore** [comment]
#901 as reference

**Comment by swamp-fish** [comment]
Its nice that an icon was fixed but husisusi also wrote that it simply doesn't work in KDE Plasma 5. Are you planing to fix it?

**Comment by antenore** [comment]
@swamp-fish ti cannot be fixed, because the KDE team have removed the xembed support.

We are thinking to remove completely the systemTray icon and develop something completely new, to simplify the Remmina usage.

One workaround, in the meanwhile, it's to use XEmbed SNI Proxy.

It should be installed by default, s just run

```sh
xembedsniproxy
```

https://github.com/KDE/plasma-workspace/tree/master/xembed-sni-proxy 

Closing this because

**Comment by giox069** [comment]
In some distributions, KDE has support for libappindicator as an alternative. It's should be called SNI/KStatusNotifierIcon, and it's the same DBus protocol as canonical's appindicator. Try to compile remmina with cmake switch -DWITH_APPINDICATOR=on and see if it works. You should install libappindicator and its development files.
