### ISSUE TITLE
Not work Copy&paste between Keepass2 and Remmina

### ISSUE THREAD

**Issue by kvaps** [FreeRDP/Remmina#900]
**This bug is crossposted on**
Remmina bug tracker: https://github.com/FreeRDP/Remmina/issues/900
Keepass bug tracker: https://sourceforge.net/p/keepass/bugs/1530/

Can not copy&paste from Keepass a field to RDP session, and back it from RDP session. (namely from the field, select and copy, not press Ctrl+C for copy password from entry list)

Example try to copy text from `URL:` or `Notes:` field to RDP session, and backeward copy text from Remmina's RDP session to Keepass2.

The problem covers only RDP connections and Keepass.
Copy&paste work fine with others programs written in mono or with freerdp runned with +clipboard option from terminal.

**Details:**
* **Client OS**: Arch Linux with last updates (also Manjaro 15.12 and Ubuntu 15.10 tested)
* **Remmina version:** 1.2.0-rcgit.11 (git n/a)
* **Keepass version:** 2.33 (Dev)
* **Mono version:** 4.4.0 (Stable 4.4.0.40/f8474c4 Mon Mar 28 12:22:29 UTC 2016)
* **Desktop environment:** naked X11 with awesome (also XFCE and Unity tested)
* **Connecting to:** Windows Server 2008 R2 and Windows 7 (may others)
* **Connecting via:** RDP (vnc work fine)
* **Freerdp version:**  2.0.0-dev (git c3ce0c3)

**Comment by antenore** [comment]
As reported by #821 , this issue should be fixed.

Can you upgrade remmina and test again please? Double check you didn't set "disable clipboard sync" (just in case)

**Comment by kvaps** [comment]
Hi, thanks for answer!

I update packages to new versions:
* **Freerdp version:** 2.0.0-dev (git c3ce0c3)
* **Remmina version:** 1.2.0-rcgit.11 (git n/a)

The problem is not solved:

* Copy from Keepass to Remmina: **not work**
* Copy from Remmina to Keepass: **not work**
* Copy from Keepass to xfreerdp: **not work**
* Copy from xfreerdp to Keepass: **work**

Copy from other apps to remmina or freerdp and back works prefictly.

**Comment by weberhofer** [comment]
Do you have TeamViewer running? There were similar issues reported with a running TeamViewer.

**Comment by antenore** [comment]
Thanks Johannes, I forgot about this.

In the meanwhile I've took a look at the KeePass code, and I see they use "Clipboard Selection", as Remmina where we use "GDK_SELECTION_CLIPBOARD"

https://github.com/keepassx/keepassx/blob/4eea7c829754b263be142e09993147763c8a8585/src/gui/Clipboard.cpp#L42

https://github.com/FreeRDP/Remmina/blob/next/remmina-plugins/rdp/rdp_cliprdr.c#L703

So it should work, except, as Johannes pointed out, TeamViewer (or whatever) "steals" the clipboard.

@kvaps even if you don't have team viewer, take a look on any other software that may use the clipboard. As far as I understand, for security reasons, KeePass empty the clipboard as soon as it has been used.

The big question is why TeamViewer is watching the clipboard? Bad code or long sight?  :-)

**Comment by kvaps** [comment]
>In the meanwhile I've took a look at the KeePass code, and I see they use "Clipboard Selection", as Remmina where we use "GDK_SELECTION_CLIPBOARD"

I thought that the problem in this, and I tryed to install clipit for syncronise `primary` selection with `clipboard` but it is not helps :(
Also I have teamviewerd service runned, not client in my host.
Remote host have no TeamViewer.
Now I stoped teamviewed service and clipit and retest copy&pase:

#### RDP
* Copy from Keepass to Remmina: **not work**
* Copy from Remmina to Keepass: **not work**
* Copy from Keepass to xfreerdp: **not work**
* Copy from xfreerdp to Keepass: **work**

Also I tested for vnc:
#### VNC
* Copy from Keepass to Remmina: **work**
* Copy from Remmina to Keepass: **work**

**Comment by kvaps** [comment]
I must remind the problem when copying from keepass occurs namely when copying plain text (select and copy), but not when copying username or password using Ctrl-B, Ctrl-C shortcuts or from context menu for entry list.

**Comment by antenore** [comment]
Ok, we will take a look. I should be able to reproduce it, but I don't know when I'll have time to investigate it deeply.

:-\ 

is there something you can do, temporary, to be able to work? Like copy&paste in a text file and then back to Remmina? Or another password manager? Just for the time needed to at least discover where the problem is laying.

**Comment by kvaps** [comment]
> I should be able to reproduce it

OK! I've seen this bug on many systems, so I think you will not be difficult to reproduce this bug.

Thank you for your concern. This problem continues from the moment as we switched to linux as main os. We are now use this workaround: copy from KeePass to text editor and from text editor to Remmina and back likewise.

**Comment by kvaps** [comment]
Hi. Still it seems that it is the Keepass bug.
Via [remote-viewer](https://virt-manager.org/) ([spice](http://www.spice-space.org/) protocol) same problem, with similar behavior:

#### SPICE
* Copy from Keepass to remote-viewer: **not work**
* Copy from remote-viewer to Keepass: **work**

**Comment by antenore** [comment]
Yes, I can systematically reproduce it as well.
By me it's keepass issue. Well for what I understand it's somehow a feature, I think they try to avoid that the password stay in the clipboard. 
I really don't know how to help. Please push with them to have an answer.

**Comment by kvaps** [comment]
I wrote a post in the Keepass tracker about my research.

But there is something no move :(
Apparently rescue of drowning, the case of drowning. (I'm talk about linux-users)

>  I think they try to avoid that the password stay in the clipboard. 

No, this problem certainly is not here, the text is not copied, even out of the window "Save as ..."
While secure copying of username or password with clipboard flushing by timeout is working properly.

**Comment by antenore** [comment]
I've also provided my feedback... Let's see

**Comment by antenore** [comment]
As for last comments at [[bugs:#1530]](https://sourceforge.net/p/keepass/bugs/1530/) there is not a feasable solution.

I keep this opened for reference.

**Comment by antenore** [comment]
Add new comments only if can resolve the issue, otherwise read carefully the full thread.

**Comment by kvaps** [comment]
I partially resolve this issue by running KeePass using dotnet under wine.
Here is my package for Arch Linux: [keepass-wine](https://aur.archlinux.org/packages/keepass-wine/)<sup>(aur)</sup>

**Comment by kvaps** [comment]
Hi! Keepass in wine did not meet my expectations, I came up with another more simplest solution:
https://github.com/kvaps/keepass-clipboard-fix
