### ISSUE TITLE
Systray does not show the remmina applet icon in Plasma 5.7 - therefore no connect menu

### ISSUE THREAD

**Issue by ShamimIslam** [FreeRDP/Remmina#944]
Please give us some details about the systems you are using:
* Client (OS name and version): Gnu/Linux 4.6.4-301.fc24.x86_64
* Remmina version (remmina --version): 1.2.0 (remmina-1.2.0-0.13.rcgit.7.fc24.src.rpm)
* Desktop environment (GNOME, Unity, KDE, ..): 4.14.10-13 (KDE) Plasma (5.7.3-1)
* Connecting to (OS and version): Windows 7
* Connecting via (RDP, VNC, ...): VNC
* RDP issues only, freerdp version (xfreerdp --version): 

I am unable to right click on the remmina icon because it does not appear in the systray.

**Comment by box293** [comment]
Can you check this issue to see if it's your problem:

https://github.com/FreeRDP/Remmina/issues/905

It confused me for a while, the icon is there it's just hard to see because of the colours.

**Comment by ShamimIslam** [comment]
In KDE 4.14/Plasma 5.7 - I do not see an entry for Remmina at all in the
system tray - as an icon or an entry. There was a deprecation of a previous
method of attaching to the system tray. I don't recall the details. I just
remember that since I started using Fedora 24, I had this problem. On
Fedora 23, I used to see the Remmina icon and Remmina entry in the system
tray. I think Fedora 23 was a previous version of Plasma. Unfortunately, I
do not have specifics. Do you need me to research?

[image: Inline image 1]

[image: Inline image 2]

[image: Inline image 3]

**Comment by HenryRc0** [comment]
Same here on fully updated Fedora 24.
Starting Remmina doesn´t create an icon in the system tray.
An entry in the "system tray settings" is created and I can choose 
between the display modes within the system tray (Auto, Hidden and Always Visible),
but whatever I choose there is no icon in the system tray.

**Comment by antenore** [comment]
System tray is something we must address as soon as possible, unlucky we don't have too many ideas and options as system trays are less and less supported by "modern" desktop environments.

Soon, also in Gtk+, we won't have anymore support for system tray (as it is today).

The biggest mess is that between Gnome, KDE, QT, Unity there is nobody able to find a common implementation. Everybody keep going in its own direction. 
For Remmina this means developing a systray substitute for each DE

I would personally prefer to get rid of the systray and implement something completely new.
We have some ideas, like implementing most of the systray features in the remmina profile editor (the main window) and the rest in the remmina connection window (the window guesting your remote connection).

If you guys have better ideas we are more than opened for discussion. We can maybe discuss this on G+ or gougle groups?

**Comment by ShamimIslam** [comment]
The system calls for the system tray have been updated. Shouldn't this be a change in the functions you are calling to reactivate the display of Remmina? If you can point me to the files where the calls are made for plasma, I can look for the replacement functions.

On August 8, 2016 8:27:34 AM EDT, Antenore Gatta <notifications@github.com> wrote:
>System tray is something we must address as soon as possible, unlucky
>we don't have too many ideas and options as system trays are less and
>less supported by "modern" desktop environments.
>
>Soon, also in Gtk+, we won't have anymore support for system tray (as
>it is today).
>
>The biggest mess is that between Gnome, KDE, QT, Unity there is nobody
>able to find a common implementation. Everybody keep going in its own
>direction. 
>For Remmina this means developing a systray substitute for each DE
>
>I would personally prefer to get rid of the systray and implement
>something completely new.
>We have some ideas, like implementing most of the systray features in
>the remmina profile editor (the main window) and the rest in the
>remmina connection window (the window guesting your remote connection).
>
>If you guys have better ideas we are more than opened for discussion.
>We can maybe discuss this on G+ or gougle groups? 
>
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/FreeRDP/Remmina/issues/944#issuecomment-238220698

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by antenore** [comment]
If you could help it'd be great, all the code of the system tray icon is in this file:

https://github.com/FreeRDP/Remmina/blob/next/remmina/src/remmina_icon.c

But we have only the appindicator and Gtk code.

**Comment by ShamimIslam** [comment]
Which version of the development change is for Remmina?

http://blog.martin-graesslin.com/blog/2014/06/where-are-my-systray-icons/

There are a number of new libraries that need to be compiled in order to
work for Plasma 5.

**Comment by giox069** [comment]
As I can see, Plasma 5 has removed the old, already deprecated by GTK3 "GtkStatusIcon" (I think it's xembed based). Remmina can work with libappindicator3, which is suppported by Plasma 5 according your blog post. But you should recompile remmina with libappindicator3 installed. Remmina should be able to find it automatically.

**Comment by ShamimIslam** [comment]
Does Remmina use libappindicator3 as a shared library? Or a static library?

I already have the following installed from
libappindicator-gtk3-12.10.0-11.fc24.x86_64

usr/lib64/girepository-1.0/AppIndicator3-0.1.typelib
/usr/lib64/libappindicator3.so.1
/usr/lib64/libappindicator3.so.1.0.0
/usr/share/doc/libappindicator-gtk3
/usr/share/doc/libappindicator-gtk3/AUTHORS
/usr/share/doc/libappindicator-gtk3/COPYING
/usr/share/doc/libappindicator-gtk3/COPYING.LGPL.2.1
/usr/share/doc/libappindicator-gtk3/README

**Comment by giox069** [comment]
Shared. You need the appropriate -devel packages (in Fedora 20 they were libappindicator-devel libappindicator-gtk3 libappindicator-gtk3-devel). And ensure that during the cmake phase there is no WITH_LIBAPPINDICATOR=no (or off) in the cmake commandline.
Take a look also at the old Fedora20 compilation guide: https://github.com/FreeRDP/Remmina/wiki/Compile-on-Fedora-20

**Comment by ShamimIslam** [comment]
OK - I will test it out. If it works, will you be updating the src.rpm in
order to make futurte Remmina builds work for Fedora 24 for the Fedora 24
packages then?

**Comment by giox069** [comment]
We are not the maintainer of the packages that you can find in various linux distributions (in this case Fedora). You should ask to the maintainer of the package.

**Comment by antenore** [comment]
@hubbitus can you please check the fedora 24 packages?
Thanks Pavel

**Comment by antenore** [comment]
While we are waiting the Pavel answer, test his COPR https://copr.fedorainfracloud.org/coprs/hubbitus/remmina-next/

**Comment by ShamimIslam** [comment]
Ok - so COPR shows that the race condition on the Gnome Keyring has been
fixed. So that part now works - it correctly asks to open the keyring
BEFORE attempting to ask me for a password when a password has been saved.
This is a good thing. This is progress.

However, the system tray issue remains.

**Comment by antenore** [comment]
Please contact Pavel directhly, in COPR you should have his contact otherwise check in the AUTHORS file, he should be there as well (Hubbitus)

**Comment by Hubbitus** [comment]
I'm very sorry for the late response.

@ShamimIslam, remmina already built with appindicator support in Fedora. Could you please test fresh versions from my copr repo?

**Comment by Hubbitus** [comment]
And I also advise you test Fedora 25 versions from official repos too.

**Comment by ShamimIslam** [comment]
I redownloaded from

[hubbitus-remmina-next]
name=Copr repo for remmina-next owned by hubbitus
baseurl=
https://copr-be.cloud.fedoraproject.org/results/hubbitus/remmina-next/fedora-$releasever-$basearch/
skip_if_unavailable=True
gpgcheck=1
gpgkey=
https://copr-be.cloud.fedoraproject.org/results/hubbitus/remmina-next/pubkey.gpg
enabled=1
enabled_metadata=1

Uninstalled and re-installed Remmina - no change. I'm going to reboot just
in case I had a stale/cached shared library.

Thanks.

**Comment by Hubbitus** [comment]
Reboot is not required.
Just give a try:
```
# dnf upgrade '*remmina*' '*freerdp*' --refresh
```

**Comment by ShamimIslam** [comment]
Tried it again your way.

Dependencies resolved.
Nothing to do.
Complete!

**Comment by Hubbitus** [comment]
What version of remmina do you have now installed?

**Comment by ShamimIslam** [comment]
remmina-1.2.0-0.19.rcgit.14.fc24.x86_64

**Comment by Hubbitus** [comment]
@antenore, that version built with appindicator support enabled:
```
WITH_APPINDICATOR=ON
```
and according to log it was already found and used:
```
-- Finding suggested package APPINDICATOR.
--   Disable this using "-DWITH_APPINDICATOR=OFF".
-- Checking for module 'appindicator3-0.1'
--   Found appindicator3-0.1, version 12.10.0
-- Found APPINDICATOR: /usr/lib64/libappindicator3.so
```

You may find full log at https://copr-be.cloud.fedoraproject.org/results/hubbitus/remmina-next/fedora-24-x86_64/00439062-remmina/build.log.gz

**Comment by ShamimIslam** [comment]
Ok - so is there a setting I have to toggle to make the indicator visible
at run-time?

Thanks.

**Comment by antenore** [comment]
thanks @hubbitus I've added the info in the main README file and I'll update the doc.

@ShamimIslam yes Preferences->Applet 

I close this, it looks like is solved (thanks to Pavel)

**Comment by ShamimIslam** [comment]
Are my settings incorrect? I still see no tray icon.

[image: Inline image 1]

When I activate Remmina, the tray icon still does not appear.

**Comment by ShamimIslam** [comment]
Can we please re-open so we can figure out what I need to do to make this
work? Should I reboot or something? Is there a way to debug what's not
working? Happy to help but I'm a little lost.

**Comment by antenore** [comment]
Sorry, I misunderstood. 

I cannot see images when you answer by mail.

@Hubbitus do you have the remmina icon applet on Plasma?

**Comment by Hubbitus** [comment]
@ShamimIslam I also want report does not see it 5 seconds ago. But It just have now so icon which I expect you may do not see depends on monitor bright settings. In my xfce session it looks like: 
![image](https://cloud.githubusercontent.com/assets/720349/17679049/65fee244-6342-11e6-97cb-f98f751757d8.png)

**Comment by ShamimIslam** [comment]
![settings-for-remmina-no-applet-visible](https://cloud.githubusercontent.com/assets/3057742/17679076/dcff8a78-6307-11e6-9399-1640c12e6031.png)

**Comment by antenore** [comment]
Pavel, for this just select "Dark Icon" in the Preferences->Applet window

**Comment by ShamimIslam** [comment]
I don't see it in plasma. I am not using XFCE.  I am using KDE. That's where my problem originated.

**Comment by ShamimIslam** [comment]
![settings-for-remmina-no-applet-visible](https://cloud.githubusercontent.com/assets/3057742/17679144/2a7b63c6-6308-11e6-94f6-55a7139842cf.png)
![system-tray-1](https://cloud.githubusercontent.com/assets/3057742/17679146/2a7f78c6-6308-11e6-980b-34a67479f711.png)
![system-tray-2](https://cloud.githubusercontent.com/assets/3057742/17679145/2a7cdff8-6308-11e6-96e5-a7bb5cdbdcb2.png)

**Comment by ShamimIslam** [comment]
![plasma-taskbar](https://cloud.githubusercontent.com/assets/3057742/17679161/3ad5b2da-6308-11e6-9a13-f6158a19b965.png)

**Comment by ShamimIslam** [comment]
Nothing to right click, no dark view or anything. When I right click, I only get the system tray settings in that blank spot next to the triangle.

**Comment by antenore** [comment]
This is still a a very old version of remmina @ShamimIslam , Pavel can you help him clean his installation?

![2016-08-15-225018_759x437_scrot](https://cloud.githubusercontent.com/assets/5975/17679215/bc2520e6-633a-11e6-9128-73244109a197.png)

**Comment by antenore** [comment]
$ remmina --version
remmina - Version 1.2.0-rcgit.14 (git 9bf3ef6)

**Comment by Hubbitus** [comment]
@antenore are you suggesting build just last commit from `next` branch or something particular?

**Comment by ShamimIslam** [comment]
$ remmina --version
remmina - Version 1.2.0-rcgit.14 (git n/a)

**Comment by ShamimIslam** [comment]
If you need me to install a different RPM, just let me know where to get it
from. I have the Remmina repo that was on hubbitus

**Comment by Hubbitus** [comment]
I believe we have you pre-release `1.2.0.rcgit.14` (which leads me surprisingly to 404 error https://github.com/FreeRDP/Remmina/tree/1.2.0.rcgit.14 from you releases tab. But tarballs loadable.).

**Comment by antenore** [comment]
@Hubbitus the last commit is too much.

Use the last release https://github.com/FreeRDP/Remmina/tree/1.2.0.rcgit.14

**Comment by Hubbitus** [comment]
That is. And exactly this URL leads to 404 error:
```
$ curl https://github.com/FreeRDP/Remmina/tree/1.2.0.rcgit.14
{"error":"Not Found"}
```

**Comment by ShamimIslam** [comment]
I have not been compiling items. Is there a SPEC file in github for FC24?
Is there a SRPM somewhere?

I don't want to end up with a mix-n-match of files leading to
unreproducible scenarios.

**Comment by Hubbitus** [comment]
Sure. All sources you could find in repo from what you install binaries: https://copr.fedorainfracloud.org/coprs/hubbitus/remmina-next/build/439062/
Off course you may get all Fedora packages sources also: http://pkgs.fedoraproject.org/cgit/rpms/remmina.git/commit/

**Comment by ShamimIslam** [comment]
Sorry - I'm a little lost. So using the hubbitus repo does not get me this version? That's what I used.

[hubbitus-remmina-next]
name=Copr repo for remmina-next owned by hubbitus
baseurl=https://copr-be.cloud.fedoraproject.org/results/hubbitus/remmina-next/fedora-$releasever-$basearch/
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/hubbitus/remmina-next/pubkey.gpg
enabled=1
enabled_metadata=1

**Comment by ShamimIslam** [comment]
I'm asking because it sounds like you are asking me to download items I may have already used. Should I re-install? Could the FC24 versions in that repo be a bad build or something?

**Comment by Hubbitus** [comment]
No, as I provide infor before there exact that version of remmina.
If @antenore said what we need build another commit I'll try to do so for you.

**Comment by giox069** [comment]
I have installed Fedora24+Plasma and compiled the latest version of FreeRDP and Remmina.
I can confirm that the statusindicator icon does not appear.
I have been able to make it appear making 2 changes
1. `APP_INDICATOR_CATEGORY_OTHER` should be changed to `APP_INDICATOR_CATEGORY_APPLICATION_STATUS` in remmina_icon.c (why ???)
2. The png format icon `remmina-panel.png` we provide with remmina is not accepted by plasma. I have no idea why it happens. I just overwrite it with a system icon and it worked.

I will investigate further in the next days.

**Comment by ShamimIslam** [comment]
Awsome. Sounds like a minor idiosyncrasy. The #define may have changed in
the newest plasma due to updates in the library - I know there was a
CHANGELOG but I had not had a chance to read it. Surprised the PNG format
is not working but oh well. Thanks for finding these.

Please let me know when I can re-run the DNF REFRESH here for testing.

Thanks.

**Comment by antenore** [comment]
@hubbitus There is something wrong with the release URL, here the right one https://github.com/FreeRDP/Remmina/tree/v1.2.0-rcgit.14

This url doesn't have the fix (we don't have a fix yet )

I wasn't expecting a problem like this at all.....

**Comment by giox069** [comment]
Fixed. There are no prolem in the use of the current .png. I have been confused by the remmina-panel.png having the same color as the KDE taskbar. But this is already addressed enabling the "Dark Tray Icon" in the global preference -> Applet menu.
So, to summarize
1. Changed in the code `APP_INDICATOR_CATEGORY_OTHER` to `APP_INDICATOR_CATEGORY_APPLICATION_STATUS`. Read a note [here](http://people.canonical.com/~ted/libappindicator/current/AppIndicator.html): "APP_INDICATOR_CATEGORY_OTHER Something not defined in this enum, please don't use unless you really need it.". Why was it used in remmina ?  :)
2. Enabled "Dark Tray icon" in global remmina settings. Closed and restarted remmina.

@Hubbitus : will COPR update automatically or should you update it mannually ?

**Comment by david-geiger** [comment]
Hi,

We have the same systray icon issue on Mageia Cauldron with plasma 5.7.x, so I confirm that using the latest git snapshot from commit 679bb8eee78765252b62aa56078a9fabe50563f8 and rebuild remmina with "-DWITH_APPINDICATOR=ON" fixes properly this systray icon issue.
N

**Comment by david-geiger** [comment]
Is it possible to release a new version "rcgit.15", please?

**Comment by Hubbitus** [comment]
679bb8eee78765252b62aa56078a9fabe50563f8 built in Fedora rawhide official repo and remmina-next copr repo for Fedora 24.
Please test.

**Comment by dd-jacks** [comment]
@Hubbitus the icon is came back)))

**Comment by antenore** [comment]
I'm going to release a new version. Thanks to everybody

**Comment by antenore** [comment]
I close this, because it'll be referenced in the changelog

**Comment by antenore** [comment]
Released https://github.com/FreeRDP/Remmina/releases/tag/v1.2.0-rcgit.15

**Comment by ShamimIslam** [comment]
I think there is a labelling problem in the FC SPEC and/or version file. But the systray icon is now visible. "rpm -q -i remmina" shows "0.21.git.679bb8e.fc24" while the "remmina --version" reports "remmina - Version 1.2.0-rcgit-14 (git n/a)".

I am seeing the systray icon though.

![remmina-systray-1](https://cloud.githubusercontent.com/assets/3057742/17713027/cc9f9424-63c6-11e6-9aa5-a71c7e09bc6a.png)
![remmina-systray-2](https://cloud.githubusercontent.com/assets/3057742/17713028/cca055c6-63c6-11e6-8e97-3be44e9e136d.png)

**Comment by ShamimIslam** [comment]
I think there is a labelling problem in the FC SPEC and/or version file. But the systray icon is now visible. "rpm -q -i remmina" shows "0.21.git.679bb8e.fc24" while the "remmina --version" reports "remmina - Version 1.2.0-rcgit-14 (git n/a)".

I am seeing the systray icon though.
![remmina-systray-1](https://cloud.githubusercontent.com/assets/3057742/17713074/0ba6c110-63c7-11e6-8d00-c6e6f8c77696.png)
![remmina-systray-2](https://cloud.githubusercontent.com/assets/3057742/17713073/0ba542a4-63c7-11e6-8476-37c7d141bc61.png)

**Comment by Hubbitus** [comment]
Last version of remmina from reemina-nex t repository should return git-revision in --version request.

**Comment by ShamimIslam** [comment]
Do you know when this version will make it to the standard repositories? I
currently have the hubbitus repo added but I'd rather not be in the test
group unless something else goes crazy. Thanks.

**Comment by ShamimIslam** [comment]
Ok - I have an issue.

I have the hubbitus repo on 2 identical machines (both F24 - S55T-C5222 and
P55W-C5314) the only difference between the two machines is the CPU in use.

On the one machine (S55T), I see the remmina tray applet. On the other,
(P55W),  I do not.

I have copied the remmina profile (.remmina) from the one machine to the
other so the setups are identical.

Please advise where I should look to track down that is going on. Please
feel free to suggest any dependencies I should confirm.

Thanks.

**Comment by ShamimIslam** [comment]
Nevermind. I have figured it out. It was my plasma - it had crashed and
needed to be restarted. I can see the icon now on both machines. Thank you.

**Comment by antenore** [comment]
Thank you.

**Comment by husisusi** [comment]
I do not know why, but since yesterday (Arch Linux Plasma Update) everything works.
Connect menu works again!!! It is great!!!!
![screenshot_20170607_125111](https://user-images.githubusercontent.com/8606735/26874985-30c88540-4b80-11e7-859b-b91fb45c9694.png)
![screenshot_20170607_125213](https://user-images.githubusercontent.com/8606735/26874989-343d9576-4b80-11e7-9d4d-1dfb2c0e7af8.png)
